version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always